Bump mypy to v0.950 (#251)
* Bump mypy to v0.950

❯ mypy pydeconz --strict
pydeconz/websocket.py:66: error: Argument 1 to "create_task" has incompatible type "Awaitable[None]"; expected "Union[Generator[Any, None, ], Coroutine[Any, Any, ]]"
pydeconz/websocket.py:93: error: Argument 1 to "create_task" has incompatible type "Awaitable[None]"; expected "Union[Generator[Any, None, ], Coroutine[Any, Any, ]]"
pydeconz/models/sensor/light_level.py:59: error: Returning Any from function declared to return "float"
Found 3 errors in 2 files (checked 54 source files)

* Replace Awaitable[None] with Coroutine[Any, Any, None]

* Use math.pow as that will always return float thus moving away from the duality of ** which returns Any